# Label- und Variablenfunktionen {#labmacro}

```{r setup3, echo = F, message=F, warning = F}
if(Sys.getenv("USERNAME") == "Filser" ) .libPaths("D:/R-library4")  # set library
# stataexe <- "C:/Program Files (x86)/Stata13/StataSE-64.exe"
stataexe <- "C:/Program Files/Stata16/StataSE-64.exe"
knitr::opts_chunk$set(engine.path=list(stata=stataexe))
library(Statamarkdown)
library(kableExtra)
library(magrittr)
# library(tidyverse)
# library(ggthemes)
```

## Arbeiten mit "Regular Expressions"


"regular expressions" oder "regex" sind eine flexible Methode, strings (also Textinhalte) zu durchsuchen. 
Dabei suchen wir nach Mustern, anstelle eines exakten matchings.

In Stata können wir regex für Variablen, aber auch für macros und Labels verwenden.
regex sind aber nicht immer die (einfachste) Lösung und oft werden die Befehle sehr unübersichtlich.
Daher hier nur eine kurzer Überblick.

Die drei Hauptfunktionen in Stata finden wir unter `help regex`:

> `regexm(s,re)` allows you to search for the string described in your regular expressions. It evaluates to 1 if the string matches the expression.
> `regexs(n)` returns the nth substring within an expression matched by regexm (hence, `regexm` must always be run before regexs).
> `regexr(s1,re,s2)` searches for re within the string (s1) and replaces the matching portion with a new string (s2).

Allerdings sind diese 

 ustrregexrf() or ustrregexra().
 
 
[Hier](https://github.com/asjadnaqvi/The-Stata-Guide/blob/master/Stata_regex_cheatsheet_v1.pdf) findet sich ein sehr gutes "Cheatsheet" zu den gebräuchlichsten regex.


## Variableneigenschaften

Um Informationen zu Variablen & Labels abzurufen, stehen eine ganze Reihe an extended macro functions zur Verfügung: 
```{stata varprop0, eval = F}
loc v m1202

local vartype:     type `v' 				  // Variablen "storage type" (byte etc)
local varlab:      variable label `v' // variable label
local vallabname:  value label `v' 	  // Name des value label
local vallab1 :    label (`v') 1		 	// Value label für Wert = 1
```

Die so erstellten `local`s können wir dann in der bekannten Methode wieder darstellen:
```{stata varprop, eval = F}
di "`vartype'"     // display local "vartype"
di "`varlab'"      // display local "varlabel"
di "`vallabname'"  // display local "valuelabname"
di "`vallab1'"     // display local "valuelab1"
```

Wir können die Labels und Eigenschaften von `v' auch in einem Schritt anzeigen lassen, die Syntax sieht aber etwas eigenwillig aus:
```{stata varprop2, eval = F}
loc v m1202
di "`: type `v''" 				   // "storage type" (byte etc) der Variable
di "`: variable label `v''"  // variable label
di "`: value label `v''" 		 // Name des value label
di "`: label (`v') 1'" 		   // Value label für Wert = 1
```




## Abgleiche 
Existiert eine Variable?
```{stata, eval = F }
capture confirm  variable lm02
if !_rc dis "ja"
if _rc 	dis	"nein"
```

Ist variable numerisch?

```{stata confnum, eval = F }
capture confirm numeric variable az
if !_rc dis "ja"
if _rc 	dis	"nein"
```

```{stata confnum,echo = F}
qui use "D:\Datenspeicher\BIBB_BAuA/BIBBBAuA_2018_suf1.0.dta", clear
capture confirm numeric variable az
if !_rc dis "ja"
if _rc 	dis	"nein"
```

`help data_types`

## wo kommt überall -4 vor?


```{stata, eval = F}
ds
local varlist1 `r(varlist)'
display "`varlist1'"
foreach v of varlist1 {
  qui count if `v' == -4
  if r(N) > 0 glo var4: display "${var4} "`v'
}
```



## Formatierung

`real()`
`help f_strofreal` Zahlen zu Text mit Formatierung



// some further things you should know:
// special macro functions (there are many), for example
```{stata, eval = F}
global sentence "here is a sentence 7"
global w2: word 2 of $sentence
mac list w2

global len: word count $sentence
mac list len
```

Variablen identifizieren and mark variables with certain properties and write them in ein `macro`
```{stata, eval = F}
ds, has(type byte)
global bytevars `r(varlist)'

foreach v of global bytevars {
	rename `v' B`v'
}
```

## Textverarbeitung

1. Mixed list with no quotes
```{stata}
local phrase 2 guys 1 girl 1 pizza place
di "`:word 2 of `phrase' '"
```



1. Mixed list with inner quotes
```{stata}
local phrase "2 guys" "1 girl" "1 pizza place"
di "`:word 2 of `phrase' '"
```
>>> Answer: guys


1. Mixed list with inner and outer quotes
```{stata}
local phrase `" "2 guys" "1 girl" "1 pizza place" " '
di "`:word 2 of `phrase' '"
```


***

**[Übung 1](#varue1)**

***



## Übungen

### Übung {#labue1}



