# Programmieren in Stata {#prog}


```{r setup5, echo = F, message=F, warning = F}
if(Sys.getenv("USERNAME") == "Filser" ) .libPaths("D:/R-library4")  # set library
stataexe <- "C:/Program Files/Stata16/StataSE-64.exe"
knitr::opts_chunk$set(engine.path=list(stata=stataexe))
library(Statamarkdown)
library(tidyverse)
library(ggthemes)
```

Seminarinhalte

Kombination von Macros und Schleifen für effizientes Programmieren sowie Macro-Funktionen (beispielsweise value label varname) gegebenenfalls in Kombination mit String- oder mathematischen Funktionen und deren Anwendung und nützliche Postestimates (beispielsweise `r(notused)`; `e(sample)`; `_b[]`) und deren Anwendung vermittelt werden.




## Macros

Macros: locals & globals (kurze Wiederholung), arbeiten mit frames, temporary variables/files/frames, tokenize, eigene Programme definieren

`help macro` durchkucken

SemiAdvanced Stata von Ludsteck

### Arbeiten `frames`

Neu seit Stata16

### Fallstricke beim Arbeiten mit Macros

+ (**Exponenten und Macros**)[https://www.stata.com/support/faqs/programming/macros-with-power-operator/]



## Fortgeschrittene Auswahl: Wildcards & regex
Wildcards, string- & regex Funktionen - Grundlagen und Anwendungsmöglichkeiten 




[beispiele](https://jearl.faculty.arizona.edu/sites/jearl.faculty.arizona.edu/files/Regular%20Expressions,%20Year%202.pdf)
https://medium.com/the-stata-guide/regular-expressions-regex-in-stata-6e5c200ef27c


## Schleifen 
 DRY ("don’t repeat yourself")

Schleifen erweitern, doFiles mit zusätzlichen Argumenten anstoßen, mehrere Sessions anstoßen


### Fehlersuche 

`set trace on`


## Postestimates

Postestimates aufrufen, verwenden und weiterverarbeiten



```{stata s5_input2}

loc t1 Hello world , this is a loop
foreach x of loc t1 {
    
	dis "`x'"
}
```



## DoFiles anstoßen

`exit, STATA`